### ISSUE TITLE
[feature request] Keyboard should open automatically when swiping to view all apps

### ISSUE THREAD

**Issue by burhanuday** [phenax/owyn-launcher#1]
I think it would be great if the keyboard opened automatically when we are viewing all apps. It makes it difficult to press the input on tall phones

**Comment by phenax** [comment]
Makes sense. I'll get it fixed.

**Comment by phenax** [comment]
This has been implemented in [0.0.2](https://github.com/phenax/owyn-launcher/releases/tag/0.0.2)
